### PR TITLE
Making Ned's changes more "Angular"

### PR DESCRIPTION
**Pull request by petefredricks**

### CODE REVIEW

**Comment by petefredricks** [comment]
@nedstankus and @andrewholsted I updated the changes to be more Angular and less jQuery. Take a look and give a thumbs up if everything makes sense. Thanks!

**Comment by holsted** [comment]
@petefredricks Nice changes. I think we should add @nedstankus's `return;` back if `scope.processing = true` to prevent duplicate calls.

**Comment by petefredricks** [comment]
@andrewholsted By disabling the button it prevents any duplicate calls. Let's make the browser handle that logic.

**Comment by holsted** [comment]
@petefredricks touche

**Pull request merged**
